# Generated by Django 3.2.9 on 2021-12-06 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portofolio',
            name='image',
            field=models.FileField(default=datetime.datetime(2021, 12, 6, 21, 31, 3, 567598, tzinfo=utc), upload_to='portofolios/'),
            preserve_default=False,
        ),
    ]
