# Generated by Django 3.2.9 on 2021-12-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_portofolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portofolio',
            name='categorie',
            field=models.CharField(choices=[('Shoot', 'Shoot'), ('Design', 'Design'), ('Web', 'Web'), ('Logiciel', 'Logiciel')], max_length=100),
        ),
    ]
